/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tsong' at '8/21/16 7:40 PM' with Gradle 2.14.1
 *
 * @author tsong, @date 8/21/16 7:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
