import org.junit.Test;

import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'tsong' at '8/21/16 7:40 PM' with Gradle 2.14.1
 *
 * @author tsong, @date 8/21/16 7:40 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
